name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@abc-widgets'
      - name: Install dependencies
        run: npm ci
        env:
          # NOTE: We're using the org's secret here for inter-repository access.
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
      - name: Run tests
        run: npm test
